import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import AosProvider from "@/Provider/AosProvider/AosProvider";
import ReactQueryProvider from "@/app/Provider/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import SiteSettingsClient from "@/components/SiteSettings/SiteSettingsClient";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "More Realty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <ReactQueryProvider>
          <Navbar />
          <AosProvider>
            <SiteSettingsClient />
            {children}
          </AosProvider>
          <Footer />
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
